# Generated by Django 4.0.6 on 2022-08-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Team', 'Team'), ('Client', 'Client')], default='Client', max_length=10, verbose_name='User Type'),
        ),
    ]
