# Generated by Django 4.0.6 on 2022-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default='', max_length=50, verbose_name='Designation'),
            preserve_default=False,
        ),
    ]
